#!/bin/bash

#Update system
sudo pacman -Syu --noconfirm

#Install yay AUR helper tool
sudo pacman -S --needed git base-devel --noconfirm
git clone https://aur.archlinux.org/yay.git
cd yay
y | makepkg -si
cd ..

#Install extra packages to setup DE
yay -S adwaita-cursors adwaita-icon-theme alacritty discord ntfs-3g dosfstools dunst neofetch firefox galculator i2c-tools jre8-openjdk mpv vlc logiops lxappearance-gtk3 man-db numlockx open-rgb pavucontrol phinger-cursors polybar picom-arian8j2-git pulseaudio-control pulseaudio-nextsink rofi solaar-git steam sxhkd thunar thunar-archive-plugin thunar-shares-plugin timeshift unrar unzip variety wine --noconfirm

#Make tmp directory and copy dotfiles
mkdir $HOME/tmp
cd $HOME/tmp/
git clone https://github.com/jacobpina1/ArchInstall-BSPWM.git
cd ArchInstall-BSPWM
cp .config $HOME/
cp .scripts $HOME/
rm -rf $HOME/tmp



