#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         3
bspc config window_gap           12
bspc config normal_border_color  "#252525"
bspc config focused_border_color  "#108E9F"
bspc config presel_feedback_color  "#89B8F7"
bspc config top_padding 	 12
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus	 true

bspc rule -a Pinentry state=floating
bspc rule -s pinentry state=floating
bspc rule -a '*:*:Picture in picture' state=floating
bspc rule -a '*:*:Picture-in-Picture' state=floating

#AutoStart applications
sxhkd &
picom &
polybar bar1 &
polybar bar2 &
polybar bar3 &
polybar bar6 &
dunst -conf $HOME/.config/dunst/dunstrc &
$HOME/.scripts/set_display.sh &
$HOME/.scripts/numlockon.sh &
$HOME/.scripts/cursorfix.sh &
$HOME/.scripts/disable_rgb.sh &
$HOME/.scripts/disable_screensaver.sh &
variety &
solaar -w hide &
